sudo: false

language: php

notifications:
  slack:
    rooms:
     - secure: "lqv6EG2khKilYd5+oMPIuiE3b24BF9Y5WxGJQCS7vLKGGVLpzSOtPWes7MYa+Q6KK8lid9RLgBWpfqkxdk/04N/rxWVbAueXCY+y9nkJfF7+VW1ah2JbQNmhXNn8oSaetIwKlIFApBC09bgKD5ql74kTfy9ciiOctT+iF/J3LLP8/KXzQ7m+0/COqeldHTy+ChQnIigIPQX7jQ9Gielm0dyTGZ7dLC12AVya7C5Or+nyfWKC34Thav77mqqaE306O+N76naOiLqMpxVmIfsRpxTpkerB8pbp+N96NdfBkWBGjpe+bFk2V6cbUBAobwDghN5WU2Ot4+IM1XrNe/z2yDYfLmW4ELVLwmgtMtWLRA863Vx0U2x5/+0BvV1/0CwkJZzwRg3vGKfGcaUeM0Oqmf+4+EmVSmlLEG4wzp5twwAFXyZXEtsR6NgL6dogL1eeFCjNbvJ9IRetBMJ9SZZO7IP2AUZBtXQKa/0btX+5+9lQn5lqmQBn7N9gGTidkPwraqHa0AzFBEmXYWUH5i9pJm7OKzTXKPGnSzJs1R/RWZr4wTpfCnuJJvi/nb4fiBUeX9+7eJruS9RFxUt8tMzvnGQsx0sw6CeQ5J8rbL3kt2EXVe0t8fzlYWfEbKRHwokXaynVYtkRr45GyLpCf02zfOS/76a6qdhNUg8/+EleFSw="
    on_success: change
    on_failure: always
  email: false

env:
  global:
    - GIT_COMMITTER_NAME=Toshihiro Kanai
    - GIT_COMMITTER_EMAIL=i@miruc.co
    - GIT_AUTHOR_NAME=Toshihiro Kanai
    - GIT_AUTHOR_EMAIL=i@miruc.co
    - secure: "jZ03RQsfz68oTLnGDw5NeWrwtu3eqSuSfzxFgTQ7QtWLfRPNqhlDkw32puoMFOnLLDPlT5YiiHatiD4uKLMyOYobKXkwPc+rQOs65vw75fI2OH+XFyKzmuA77WN0A1JncX2GypvDCdS4dSWEzb4tOcyE42WWnlNchpFQRLLz5f7xc1trQR1w6fZlNyhKJdVPpEt9qtJlwXQlAMZOCDMkQevCB4WEnQbiw4973CYRL2rL/YkqpmMfnwCjwvRXHgcQJb7H1setLcBfYlK4LmzNL9FJ6JF7h/MoKM/CDE88cuQAdGDe8neJPBBamneGssBkJM7+t4GMmjWpXHDXpNwInZZEC+ARgB1A/pdJN3XBHMaCpsoBjiaiTI5ebeH320qTy+koGjHwIortJ1olsoS51iPNrZFj1MYeBIigVsU2eJ3b/XX7wR0gGLdles4p7h41yNYJZisr5pTFbXlJiIkKQHYgWHWGhzkfqaUNKhqQu692hkl8IiJOPbepXUhkCAx8JE+NsMg7Ap+e6GdQQRMEXfvd5A2k2cAfFVMNENC7mq3bhAnAO7Pmd8xKdU4LsdvnSvQaXaZYZ9Aj4QRYoagS162gE+fTx4catRDRr5DlhyHneFQAkA/mLjq3/hIXlmbVOkvpoin/WINrcgnmc9cggkEmveNcBKxSgwqv39honvM="

branches:
  only:
    - master
    - /^greenkeeper/.*$/

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - node_modules

before_install:
  - nvm install 10
  - npm i -g yarn
  - yarn global add greenkeeper-lockfile

install:
  - yarn install

matrix:
  include:
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.6
      env: WP_TRAVISCI=phpcs

before_script:
  - |
    if [[ "7.2" == "$TRAVIS_PHP_VERSION" ]] ; then
      greenkeeper-lockfile-update
    fi
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
        composer global require "phpunit/phpunit=4.8.*"
      else
        composer global require "phpunit/phpunit=5.7.*"
      fi
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      rm -f composer.lock
      composer install
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer run lint
    fi
  - yarn build

after_script:
  - |
    if [[ "7.2" == "$TRAVIS_PHP_VERSION" ]] ; then
      greenkeeper-lockfile-upload
    fi

after_success:
  # Run npm build task.
  - bash ./bin/deploy.sh
