name: Deploy to dist branch
on:
  push:
    branches:
      - master

jobs:
  Deploy:
    name: Copy necessary files
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Get Node version
        id: node_version
        run: |
          VERSION=`cat .nvmrc`
          echo ::set-output name=value::$VERSION
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node_version.outputs.value }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn
          restore-keys: ${{ runner.os }}-yarn

      - name: yarn install
        run: yarn install --prefer-offline

      - uses: actions/checkout@v2
        with:
          ref: dist
          path: dist

      - name: Build
        run: yarn build

      - name: Set commit author
        run: |
          git config --global user.name 'Toshihiro Kanai'
          git config --global user.email 'mirucon@users.noreply.github.com'

      - name: Commit
        working-directory: ./dist
        run: git commit -am "Update from travis ${{ github.shagst }}"
        continue-on-error: true

      - name: Push
        working-directory: ./dist
        run: git push origin dist:dist
